### ISSUE TITLE
Esp32 S2 Mini V1.0.0 please

### ISSUE THREAD

**Issue by MBlackmagic** [thelastoutpostworkshop/gpio_viewer#1]
It would be great if you can integrate the Esp32 S2 Mini V1.0.0 board, thank you very much.

![620019105_max 1](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/39409854/a41ae7a3-5e35-43ac-ae40-297456deae9e)

**Comment by thelastoutpostworkshop** [comment]
The board has been added and is now available.
