### ISSUE TITLE
GPIO Viewer

### ISSUE THREAD

**Issue by Alzburg** [thelastoutpostworkshop/gpio_viewer#103]
In file included from C:\Users\jhmax\AppData\Local\Temp\.arduinoIDE-unsaved2024124-5872-1df5n7z.rb36\gpioviewer\gpioviewer.ino:8:
c:\Scatchbook\libraries\GPIOViewer\src/gpio_viewer.h: In member function 'int GPIOViewer::readGPIO(int, uint32_t*, pinTypes*)':
c:\Scatchbook\libraries\GPIOViewer\src/gpio_viewer.h:525:33: error: 'analogGetChannel' was not declared in this scope; did you mean 'analogChannel'?
  525 |         uint8_t analogChannel = analogGetChannel(gpioNum);
      |                                 ^~~~~~~~~~~~~~~~
      |                                 analogChannel

exit status 1

Compilation error: exit status 1

Hi everyone, I'm trying to install the GPIO Viewer on the ESP32 Dev Module and it keeps giving me this error, can you please advise me what I'm doing wrong when I did everything according to the instructions and the Youtube video? Thank you and have a nice day.

**Comment by thelastoutpostworkshop** [comment]
Your probably not on the latest version of ESP32 boards for Arduino.  Update to the latest version.

**Comment by Alzburg** [comment]
In file included from C:\Scatchbook\gpioviewer\gpioviewer.ino:8:
c:\Scatchbook\libraries\GPIOViewer\src/gpio_viewer.h: In member function 'int GPIOViewer::readGPIO(int, uint32_t*, pinTypes*)':
c:\Scatchbook\libraries\GPIOViewer\src/gpio_viewer.h:525:33: error: 'analogGetChannel' was not declared in this scope; did you mean 'analogChannel'?
  525 |         uint8_t analogChannel = analogGetChannel(gpioNum);
      |                                 ^~~~~~~~~~~~~~~~
      |                                 analogChannel

exit status 1

Compilation error: exit status 1



https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html


I tried the ESP update from this page, then restarted the Arduino IDE and it says this. I'm already an old man of 60 years, so I can't move about it somehow :-( Thank you for your effort!

**Comment by thelastoutpostworkshop** [comment]
You have to do the board update through the Arduino IDE in the boars manager.

**Comment by Alzburg** [comment]
Do you have a name please, besides the ones I have installed?
![Screenshot 2024-02-24 at 19-29-48 Překladač Google](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/131798488/0bea0216-b659-4c25-ba73-a410a711209d)

**Comment by Alzburg** [comment]
![obrazek](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/131798488/74490ecd-4875-4a28-a6b3-e3b3f70ffe8a)

**Comment by Alzburg** [comment]
Do you have a name please, besides the ones I have installed?

**Comment by thelastoutpostworkshop** [comment]
You have an alpha version installed (3.0.0a) in the dropdown menu, choose version 2.0.14 
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/127604345/36763411-b478-46fc-ad8d-a3ec2f9f60d8)

**Comment by Alzburg** [comment]
![obrazek](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/131798488/99370226-bcc8-4433-846a-3eb567a422fc)

**Comment by Alzburg** [comment]
I don't have this version.

**Comment by thelastoutpostworkshop** [comment]
2.0.11 should work

**Comment by Alzburg** [comment]
Bingo! It works! Thank you very much for your quick help and have a nice night! Greetings from the Czech Republic! Hello!

**Comment by thelastoutpostworkshop** [comment]
Glad it works!
