### ISSUE TITLE
Add request: ESP32-S2 / S3 / C3 / SAMD21 / RP2040 / Pico / on Adafruit QT-PY (all same graphic)

### ISSUE THREAD

**Issue by NGL3324** [thelastoutpostworkshop/gpio_viewer#107]
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/41494356/13dd8368-bfcc-4b6f-83d9-9072bc760d64)

**Comment by thelastoutpostworkshop** [comment]
what board is the image above, please provide a link to the board.
