### ISSUE TITLE
Add Waveshare ESP32C3-Zero to GPIO-Viewer

### ISSUE THREAD

**Issue by thomas-lentz** [thelastoutpostworkshop/gpio_viewer#108]
Can you please add the [Waveshare ESP32C3-Zero](https://www.waveshare.com/wiki/ESP32-C3-Zero) to GPIO-Vierwer?
![1711709161824-604](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/53970628/73daf1fe-a68c-47c4-ab90-fedd2447881e)

Thank you for your work
Greetings
 Tom

**Comment by thelastoutpostworkshop** [comment]
The board is now available.

**Comment by thomas-lentz** [comment]
Thank you, that was really quick. Now I have to figure out, why the model is not shown in the Tasmota GPIO-Viewer section...

**Comment by arendst** [comment]
If you use Tasmota v13.3.0 you won't see it as this version uses a different hosted version of gpio_viewer for legacy reasons. Just change to the current live hosted gpio_viewer using command gpurl or install current tasmota dev release.
