### ISSUE TITLE
Add NodeMCU ESP32 30 Pin

### ISSUE THREAD

**Issue by Rottenbeer** [thelastoutpostworkshop/gpio_viewer#109]
Hey :)

Could you please add this board?
I'd have done it if I could find where in this repo

https://arduino-projekte.info/produkt/node-mcu-esp32-30pin/
![nodemcu_esp32_30pin](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/2014982/0748aa32-fcc5-4910-a68e-3f0e342452eb)

**Comment by thelastoutpostworkshop** [comment]
The board is already available, it's called "[ESP32 VROOM 32D (30 pins)](https://github.com/thelastoutpostworkshop/microcontroller_devkit/blob/main/gpio_viewer_1_5/devboards_images/ESP32-VROOM-32D-30pins.png)"
