### ISSUE TITLE
Add Request - ESP32 Dev Kit C V4

### ISSUE THREAD

**Issue by GEDValdi** [thelastoutpostworkshop/gpio_viewer#112]
Hi, thank you for the great idea, it is really helpful.
I would be very happy if you could add also the ESP-32 Dev Kit C V4 board.
Here is also a link to the exact board: https://www.az-delivery.de/en/products/esp-32-dev-kit-c-v4

Thanks,
Georgi

**Comment by thelastoutpostworkshop** [comment]
it's the same as ESP32-VROOM-32D (38 pins)

**Comment by GEDValdi** [comment]
Great, thank you!
