### ISSUE TITLE
Board Request - SparkleIoT ESP32-C3F

### ISSUE THREAD

**Issue by lightmaster** [thelastoutpostworkshop/gpio_viewer#115]
As someone pointed out in the Tasmota repo (https://github.com/arendst/Tasmota/discussions/21326), I'm adding a request here to add SparkleIoT ESP32-C3F (and should be the same with other ESP32-C3F boards). Board and its information is available on their Amazon page (https://www.amazon.com/gp/product/B0BNWTCPV8/).

Picture of Front
![ESP32-C3F Picture](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/5307827/93c86174-ff2f-461a-82f1-abc5f560af3f)

Pinout from front
![ESP32-C3F Pinout](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/5307827/eccffd45-a31e-4fd9-9eee-8ac3d5801f89)

**Comment by thelastoutpostworkshop** [comment]
The board is now available

**Comment by lightmaster** [comment]
Thanks
