### ISSUE TITLE
Support ESPRESSIF ESP32-S3-DevKitC-1

### ISSUE THREAD

**Issue by mphohio** [thelastoutpostworkshop/gpio_viewer#117]
please add the Espressif ESP32-S3-DevKitC-1 to the list of boards available in the GPIO Viewer app.

Link to image:
 
![ESP32-S3-DevKitC-1](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/27784508/6a939236-634b-4904-adf5-af24fd5e4302)

**Comment by thelastoutpostworkshop** [comment]
It is already there, it's called "ESP32-S3-Wroom-1"

**Comment by mphohio** [comment]
When I initially looked at the board I noticed that the physical layout was different and moved on.  I now wee that the pins do correspond to the unit I have.  Thanks,
