### ISSUE TITLE
Request for an ESP32-devkitC board

### ISSUE THREAD

**Issue by enmann59** [thelastoutpostworkshop/gpio_viewer#119]
GPIOviewer is a great tool!  I really enjoy it!  I'd appreciate support for the ESP32-devkitC board if/when you get an opportunity.

Links for information from the Espressif are below:
Board Picture: [https://www.espressif.com/sites/default/files/dev-board/ESP32-DevKitC_S_0.png](url)
Pin Description: [https://docs.espressif.com/projects/esp-idf/en/latest/esp32/_images/esp32-devkitC-v4-pinout.png](url)
ESP32-DevKitC getting started guide: [https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-devkitc.html](url)

For future reference, do you prefer links to board information or to have files attached?

Thank you for this terrific application!

Looks like the attached png board picture is too small ... below is a much better image (jpeg):

![MFG_ESP32-DEVKITC-32UE](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/169423394/3b87a7ac-3709-4f15-8b28-2c9890b7f566)

This is from the following (very long) digikey link: [https://www.digikey.com/en/products/detail/espressif-systems/ESP32-DEVKITC-32UE/12091813?utm_adgroup=&utm_source=google&utm_medium=cpc&utm_campaign=PMax%20Shopping_Product_Low%20ROAS%20Categories&utm_term=&utm_content=&utm_id=go_cmp-20243063506_adg-_ad-__dev-c_ext-_prd-12091813_sig-Cj0KCQjw6PGxBhCVARIsAIumnWYM5k0N39cxg55_NZvXXP8zl55g4as80ikv2qVeHRhnBAWI-IIkZWkaAgoKEALw_wcB&gad_source=1&gclid=Cj0KCQjw6PGxBhCVARIsAIumnWYM5k0N39cxg55_NZvXXP8zl55g4as80ikv2qVeHRhnBAWI-IIkZWkaAgoKEALw_wcB](url)

**Comment by thelastoutpostworkshop** [comment]
Thank you.  The way you submitted it is perfect, links with a board image.

**Comment by enmann59** [comment]
Thank you!  This appear to be the same module as the ESP32 Wroom 32UE ... not sure if I missed this earlier (I thought I carefully checked all the modules) but it's here now!

Using ESP32 Wroom 32UE is working great for me

I will close this request with this comment.

BTW - went through your source code at the base URL (https://thelastoutpostworkshop.github.io/microcontroller_devkit/gpio_viewer_1_5) ... brilliant!  Thank you again.

**Comment by enmann59** [comment]
I am using ESP32 Wroom 32UE now which appears to match the ESP32-DevKitC and it works great!  Thanks again for your excellent project!
