### ISSUE TITLE
Not showing IP address

### ISSUE THREAD

**Issue by icaros83** [thelastoutpostworkshop/gpio_viewer#123]
I've included the code as shown and the serial monitor reports "connected to wifi" but doesn't return an IP address.
At first I thought it was because I was using port 8080 elsewhere so I changed it to no avail.
I cannot see the connection on my router so not sure what is going on?
Please see attached screen grab
![screen grab to github](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/36670316/49a6fbf7-8969-40c9-8ce7-f2f0480610ae)

Thanks

**Comment by thelastoutpostworkshop** [comment]
What is the version of Espressif Arduino are you using for your board ?ç
I see a PSRAM read error, what are the specific configuration for your board in the Arduino IDE ?

**Comment by icaros83** [comment]
Thank you for such a quick response.

Do you mean this "esp-2021r2-patch5-8.4.0"?
Not sure what the second question is asking but the board selected is the uPesy ESP32 wrover devkit, I have also tried ESP32 wrover.
________________________________

**Comment by icaros83** [comment]
I've tried the test program and all I get from the ESP32 is a row of dots.
________________________________

**Comment by thelastoutpostworkshop** [comment]
In the Ardnuio IDE, if you go to the boads: smanager:
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/127604345/d78a0882-824a-4438-8b21-f25683122595)

You should see the boards version you are using :
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/127604345/6a0608ab-89a4-46d1-8811-e1b85cdbcc52)

The configuration of your specific board are availaible in the tools menu :
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/127604345/1a20b42a-580f-4172-9bc8-839d5ad1bfff)
