### ISSUE TITLE
Nothing is shown in serial monitor

### ISSUE THREAD

**Issue by vitalickr** [thelastoutpostworkshop/gpio_viewer#125]
Hello,

I compiled and uploaded the example code as is (changed only ssid and pwd) but nothing is showing in the serial monitor window. "Arduino ESP32 Boards" is 2.0.13, "esp32 by Espressif Systems" is 2.0.17 (won't compile with the latest 3.0.0), GPIOViewer is 1.5.3. Arduino IDE 2.3.2.

Simple_server example that comes with ESPAsyncWebServer compiles and works just fine with the same credentials, including serial monitor output.

**Comment by thelastoutpostworkshop** [comment]
Maybe it's a silly question, but what you show above is from the compiler output window, did you open the Serial Monitor in the IDE ?

**Comment by vitalickr** [comment]
> Maybe it's a silly question, but what you show above is from the compiler output window, did you open the Serial Monitor in the IDE ?

Of course, there was nothing to show from the serial monitor window as it was empty. I just figured it out: I added a short delay after Serial.begin(115200) in setup() and it started working.
