### ISSUE TITLE
Please add nanoESP32-C6

### ISSUE THREAD

**Issue by rgarzar** [thelastoutpostworkshop/gpio_viewer#127]
Board
https://uelectronics.com/wp-content/uploads/2023/11/AR3836-ESP32-C6-DevKit-Placa-de-Desarrollo-Dual-Tipo-C-Pinout.jpg
Info:
https://uelectronics.com/producto/esp32-c6-devkit-dual-tipo-c-nanoesp32-c6-v1/
Github:
https://github.com/wuxx/nanoESP32-C6#%E4%BA%A7%E5%93%81%E9%93%BE%E6%8E%A5
Datasheet:
https://uelectronics.com/wp-content/uploads/2023/11/AR3836-ESP32-C6-DevKit-Placa-de-Desarrollo-Dual-Tipo-C-Datasheets.pdf

Thanks!

**Comment by thelastoutpostworkshop** [comment]
The board is now avalaible.

**Comment by rgarzar** [comment]
Thanks!
