### ISSUE TITLE
New Board: ESP32-S3-DevKitM-1-N8 

### ISSUE THREAD

**Issue by Marek128b** [thelastoutpostworkshop/gpio_viewer#128]
## Board top down
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/58476072/1ad23c45-9931-4de3-bdfb-48b9b9256b35)

## Pinout 
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/58476072/6c771fd4-aa1d-4213-8271-b2bab6bd3428)

**Comment by thelastoutpostworkshop** [comment]
The board is now available.
