### ISSUE TITLE
add esp32 devkit 36 pins

### ISSUE THREAD

**Issue by fragolinux** [thelastoutpostworkshop/gpio_viewer#129]
please add this model, very useful with the additional shield... thanks!

![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/21192010/b70730e8-bbeb-4085-a3a3-e3d483575b83)

**Comment by thelastoutpostworkshop** [comment]
The 36 pins dev board is already there.

**Comment by fragolinux** [comment]
> The 36 pins dev board is already there.

ehm... "there" where? i just checked each and every one shown here: https://github.com/thelastoutpostworkshop/gpio_viewer
and none of them is similar to the one i posted (with 3v3, clk and sd0 at the opposite corner of the en one)

**Comment by thelastoutpostworkshop** [comment]
Please provide a link to the pinout of this board along with a link showing the board viewed from the top

**Comment by fragolinux** [comment]
> Please provide a link to the pinout of this board along with a link showing the board viewed from the top

![image](https://github.com/user-attachments/assets/887344c0-9a47-46c0-bf35-37bde599a8fb)

from: https://it.aliexpress.com/item/1005006306428914.html

![image](https://github.com/user-attachments/assets/919368e7-94a6-40d9-8914-db53b727b303)

from: https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

**Comment by thelastoutpostworkshop** [comment]
The boars is now available as ESP32 DEVKIT V1 (36 pins)

**Comment by fragolinux** [comment]
thank you!

**Comment by fragolinux** [comment]
but i don't see it listed, nor new commits to you repo...
