### ISSUE TITLE
Please add board nodemcu32s

### ISSUE THREAD

**Issue by ThinhAE22** [thelastoutpostworkshop/gpio_viewer#130]
https://www.botnroll.com/pt/esp32/3540-esp32-placa-de-desenvolvimento-wifi-bluetooth-esp-32s-ai-thinker.html

**Comment by trip5** [comment]
This is a common board for me so here you go:

![NodeMCU-32S-details-3](https://github.com/user-attachments/assets/fd35b7fe-9649-4490-824e-1100119cd1e2)

**Comment by thelastoutpostworkshop** [comment]
The board is now available.
