### ISSUE TITLE
ESP32 board request: KeeYees ESP32 Mini (Chip ESP-WROOM-32)

### ISSUE THREAD

**Issue by joergspiegel** [thelastoutpostworkshop/gpio_viewer#133]
It would be nice if the following board could be added:

![81vNWANsnZL _AC_SX679_](https://github.com/user-attachments/assets/2eb59c33-49cd-4312-991f-44e8e0e064ae)
![716ZkVq1xQL _AC_SX679_](https://github.com/user-attachments/assets/a124a125-6d68-4c84-a5a7-6d129e7a0b5b)

https://www.amazon.de/dp/B08TBPBJGV?psc=1&ref=ppx_yo2ov_dt_b_product_details

**Comment by thelastoutpostworkshop** [comment]
The board is already there, it's called : Wemos D1 Mini ESP32
