### ISSUE TITLE
Please, could you add the ESP32 WROOM 32D board.  Thanks

### ISSUE THREAD

**Issue by BLACKSHEEPVZLA** [thelastoutpostworkshop/gpio_viewer#145]
https://forum.arduino.cc/t/cant-download-code-to-esp32-wroom-32d/659376

**Comment by thelastoutpostworkshop** [comment]
You can use ESP32 Wroom-32UE, it's the same pinout and almost exactly the same appearance.

**Comment by BLACKSHEEPVZLA** [comment]
Thanks a lot for your response.
I Will do that.
