### ISSUE TITLE
Support for platform.io

### ISSUE THREAD

**Issue by cgreening** [thelastoutpostworkshop/gpio_viewer#16]
Can you add this library to platform.io

At the moment I think you are missing`library.json` which means you can't use this from platform.io

```
MissingPackageManifestError: Could not find one of 'library.json, library.properties, module.json' manifest files in the package
```

https://docs.platformio.org/en/latest/manifests/library-json/index.html

**Comment by cgreening** [comment]
Actually, I see that this isn't used as a library. Feel free to ignore this issue if the intended use is to download the code.

**Comment by thelastoutpostworkshop** [comment]
A pull request for this is pending : https://github.com/thelastoutpostworkshop/gpio_viewer/pull/5
