### ISSUE TITLE
Please add OLIMEX ESP32-POE

### ISSUE THREAD

**Issue by rolandheidy** [thelastoutpostworkshop/gpio_viewer#2]
is:issue is:open Please add OLIMEX ESP32-POE - its ESP32+Ethernet board. The data are here https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware

**Comment by Mergenth** [comment]
Please add the C3-Mini

Pinout:   https://www.wemos.cc/en/latest/_static/boards/c3_mini_v2.1.0_4_16x9.png

![C3-Mini_transparent](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/17668163/3793c3d1-5d0d-4f2a-a1ba-fe3c37140fc0)

**Comment by rolandheidy** [comment]
ESP32-POE Pinouts https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/resources/ESP32-POE-GPIO.png

**Comment by thelastoutpostworkshop** [comment]
The ESP32-POE is now added

**Comment by thelastoutpostworkshop** [comment]
The ESP32-C3-Mini is now added
