### ISSUE TITLE
LILYGO® TTGO T7 Mini32 V1.5

### ISSUE THREAD

**Issue by anwa** [thelastoutpostworkshop/gpio_viewer#21]
I recently came across your video and was inspired to immediately install your library. I'm delighted to report that it worked seamlessly with my TTGO T7 Mini32.

I am writing to kindly request the inclusion of the LILYGO® TTGO T7 Mini32 V1.5 board in your library. Despite my efforts to figure out how to add it myself, it seems that this might not currently be feasible. If possible, I would greatly appreciate any guidance or instructions you could provide on this matter.

For your reference, here are the relevant links:

Homepage: https://www.lilygo.cc/products/t7-mini32-v1-5
GitHub: https://github.com/LilyGO/TTGO-T7-Demo

Thank you for considering my request. I believe that including this board could benefit many users of your library.

Best regards,
Andreas

**Comment by thelastoutpostworkshop** [comment]
The board is now available.
