### ISSUE TITLE
Seed ESP32c

### ISSUE THREAD

**Issue by BishAU** [thelastoutpostworkshop/gpio_viewer#31]
![pin_map-2](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/29667926/f396509c-ce94-42fc-a8f2-6ad311a41280)

https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/

How can I help?

**Comment by thelastoutpostworkshop** [comment]
The board is now available.
