### ISSUE TITLE
basic functionality doesn't work for me

### ISSUE THREAD

**Issue by danny-water** [thelastoutpostworkshop/gpio_viewer#36]
Hi, 
Looks like awsome project, tried it, I see the web page but no blinking led, all gpios are constatntly off.
this is my code:

/***
This example is intended to demonstrate the use of the GPIO Viewer Library.

Tutorial : https://youtu.be/UxkOosaNohU
Documentation : https://github.com/thelastoutpostworkshop/gpio_viewer
***/

#include <gpio_viewer.h> // Must me the first include in your project
GPIOViewer gpio_viewer;

void setup()
{
  Serial.begin(115200);

  // Comment the next line, If your code aleady include connection to Wifi
  gpio_viewer.connectToWifi("ssid", "pass");
  // gpio_viewer.setPort(5555);                 // You can set the http port, if not set default port is 8080

  // Your own setup code start here
  pinMode(2, OUTPUT);
  digitalWrite(2, HIGH); // turn the LED on

  // Must be at the end of your setup
  // gpio_viewer.setSamplingInterval(25); // You can set the sampling interval in ms, if not set default is 100ms
  gpio_viewer.begin();

  
}

// You don't need to change your loop function
void loop() {
  
  digitalWrite(2, HIGH); // turn the LED on
  delay(500);             // wait for 500 milliseconds
  digitalWrite(2, LOW);  // turn the LED off
  delay(500);  
}
// The rest of your code here

![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/33643105/1b772979-b335-4db1-a669-6c5937f584e3)

- BTW - I see the LED blinking on the board, anything obvious i'm missing ?

**Comment by thelastoutpostworkshop** [comment]
What is the URL you get on the Serial Monitor ?

**Comment by danny-water** [comment]
http://192.168.1.93:8080

**Comment by thelastoutpostworkshop** [comment]
I don't have this board, but it should work.  Have you make it work with another board ?
If you use the generic view, do you see pin 2 blink on the application ?

**Comment by danny-water** [comment]
not sure I have another board, will try to find.
unfortunately I don't see pin 2 blink on the generic board as well

**Comment by thelastoutpostworkshop** [comment]
if you refresh your browser, you should see a message on the Serial monitor indicating that the ESP32 is connected to the web application : 
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/127604345/b4ad7fd1-666d-4d05-ba04-c1f4a686468a)

**Comment by danny-water** [comment]
yeah, I see that every time I refresh.
but also I see 0 channels are used .
I'm using a different chip, same thing.

I'm using arduino IDE version 1.8.19 - maybe that the problem ?

Here is the printout from the serial monitor:
================================
Chip Model: ESP32-S3
Chip version: 0
Numer of cores: 2
Flash Chip Size: 8388608
Flash Chip Speed: 80000000
================================
0 pins are PWM
0 channels are used
GPIOView Web Application URL is: http://192.168.1.93:8080
GPIO View Connected, sampling interval is 100ms
GPIO View Connected, sampling interval is 100ms
GPIO View Connected, sampling interval is 100ms

**Comment by thelastoutpostworkshop** [comment]
yes if possible try it on version Arduino 2

**Comment by thelastoutpostworkshop** [comment]
other question, are you seeing Free Heap memory changing ?

**Comment by danny-water** [comment]
The heap was not changing as well.
tried the arduino 2 ide and it works great !!!

![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/33643105/99202044-7d53-4545-a73e-b295c45aebc2)

Thank you so much for your great and quick responses !!

**Comment by thelastoutpostworkshop** [comment]
Glad it's working!
