### ISSUE TITLE
GPIO viewer does not work

### ISSUE THREAD

**Issue by Marcelverhoeven** [thelastoutpostworkshop/gpio_viewer#38]
I installed the latest release of GPOI viewer (1,0,3)
I installed https://github.com/me-no-dev/ESPAsyncWebServer
I entered in the gpioviewer.ino (= example code)  my SSID and Pass
I have added code:
 In the setup: pinMode(4, OUTPUT); and digitalWrite(4, LOW);
 In the loop: digitalWrite(4, HIGH); delay(1000); digitalWrite(4, LOW);  delay(1000);

The Led connected to GPIO is flashing  as expected at the rate of 1 sec,
I also restated Arduino,

On my browser I see the Picture of the ESP DevKit v1 but ALL pins remain at "0"
What might be the issue???

**Comment by thelastoutpostworkshop** [comment]
What view are you using in the web application ?

**Comment by Marcelverhoeven** [comment]
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/47078286/5a8e8383-defe-4fc5-91a9-7d218d9deae6)

I also tried several other views and port 8080 and 5555

still the same issue

**Comment by thelastoutpostworkshop** [comment]
if you refresh your browser, you should see a message on the Serial monitor indicating that the ESP32 is connected to the web application :
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/127604345/a86501b4-9ca4-4801-a709-72cd48b74ec6)

**Comment by Marcelverhoeven** [comment]
That is correct:
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/47078286/aadb8018-6386-4940-ac96-a88ce4978199)

**Comment by Marcelverhoeven** [comment]
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/47078286/be2dd44c-04d7-4af2-a682-771c574a8bac)

I also tried port 
8080 and 5555

**Comment by Marcelverhoeven** [comment]
Note: Free heap and Free Sketch are alive
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/47078286/59173325-aeb0-4037-a671-50bb48770368)

But no GPIO info

**Comment by thelastoutpostworkshop** [comment]
Try clearing your browser cache data.
Also, do you see the value of free heap changing ?

**Comment by Marcelverhoeven** [comment]
Try clearing your browser cache data ==> DONE
Also, do you see the value of free heap changing ==> YES
No solution,

**Comment by thelastoutpostworkshop** [comment]
that is strange, have you the latest version of Espressif boars : 
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/127604345/8eb06ea0-7cda-42ad-a913-e2b35d1081f5)

**Comment by wazzaguy** [comment]
I was experiencing the same problem but got it to work.
I had to downgrade the board from version 2.0.14 to 2.0.11 and recompile.
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/10154316/2814e172-3c7b-4097-bd87-732371c5d773)

**Comment by thelastoutpostworkshop** [comment]
Thanks for you help @wazzaguy, I am going to do some test with version 2.0.14

**Comment by thelastoutpostworkshop** [comment]
Just tested the library against Espressif Esp32 boars v.2.0.14 (latest version) and everything is working

**Comment by wazzaguy** [comment]
I updated from 2.0.11 to 2.0.14 and its not working again.
@Marcelverhoeven does downgrading to 2.0.11 work for you?

@thelastoutpostworkshop which Board Manager URL are you using?
I'm using https://espressif.github.io/arduino-esp32/package_esp32_index.json

**Comment by thelastoutpostworkshop** [comment]
@wazzaguy I have used the boards manager in the Arduino IDE 2 : 
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/127604345/6aa6a9bd-b86c-42aa-89e9-d2dc576a1485)

**Comment by thelastoutpostworkshop** [comment]
This is the library : https://github.com/espressif/arduino-esp32

**Comment by whilexx** [comment]
This Worked for me as well. The Board version is the Problem 2.0.11 works fine. BTW, great tool. Thx.

**Comment by KwangYeonCHO** [comment]
I also encountered the same problem, web server, development board images, IO not working, always in 0.  [ VSCODE PLATFORM]

**Comment by labixlerOSL** [comment]
I had the same issue. I rolled back to 2.0.11 and it works.

**Comment by thelastoutpostworkshop** [comment]
I am kind of thinking that the reinstallation of the ESP32 boards solve the problem, if someone could try to go back to 2.0.14 to test it again please.

**Comment by thelastoutpostworkshop** [comment]
Thanks for trying it, I will have to investigate further.  As for the activities, this could be "floating pins", the library reads the actual value of the pins

**Comment by Lynetk** [comment]
> I updated to 2.0.14 and it was no longer working. I have reverted to 2.0.11 and it is now showing something again. I have noticed, however, that there seems to be a lot of activity for a very basic program. All I am doing at the moment is flashing a single LED, but 14 other pins are randomly switching state.

Same "issue" for me. 2.0.14 not working with s2 mini board. Reverting to 2.0.11 gets it going, but there is a lot of activity on non-used pins and after about 20-30 seconds the board resets and it takes some time to get back up. This pattern repeats itself.

I also run a simple blink program and use the LOLIN S2 Mini

```
GPIOViewer gpio_viewer;
#define LED_GPIO 1

void setup()
{
  Serial.begin(115200);
  gpio_viewer.connectToWifi("removed", "removed");
  pinMode(LED_GPIO, OUTPUT);
  gpio_viewer.begin();
}

void loop() {
  digitalWrite(LED_GPIO, HIGH);
  delay(1000);
  digitalWrite(LED_GPIO, LOW);
  delay(1000);  
}
```

**Comment by Marcelverhoeven** [comment]
I installed 2,0,11 and it works!
This is really a great library!!!
I am not strong enough to find out why 2,0,13 does not work ==> It would be nice if someone could put his teeth in it.
I will recommend it to my friends.
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/47078286/c1e736d1-c4a0-416f-a7ed-7bd71649f4fa)

**Comment by thelastoutpostworkshop** [comment]
Glad it's working now
