### ISSUE TITLE
Request for adding TinyPICO Nano board

### ISSUE THREAD

**Issue by toetoast** [thelastoutpostworkshop/gpio_viewer#39]
Hi, 

The TinyPICO Nano board is a ESP32 PICO D4 board from Unexpected Maker.
Photos, pinouts & details are here:

https://unexpectedmaker.com/shop.html#!/TinyPICO-Nano/p/578888860/category=154494282

Many thanks
Tony

**Comment by thelastoutpostworkshop** [comment]
The board is now available.
