### ISSUE TITLE
Please to create the board Arduino Nano ESP32

### ISSUE THREAD

**Issue by bioz75** [thelastoutpostworkshop/gpio_viewer#40]
https://europe1.discourse-cdn.com/arduino/original/4X/d/6/f/d6fef98eecc68220a901d5f313301b0c2353a580.png

or 

https://docs.arduino.cc/static/25d72b1ee8a7c398e7d0700c7f029fac/e8950/esp-pinout.png

thanks in advance

Fred

**Comment by thelastoutpostworkshop** [comment]
It is already available, it's called Nano ESP32 in the web application, if you don't see it.  Clear your browser data cache, and refresh the window
