### ISSUE TITLE
ESP32-S3 Dev Module

### ISSUE THREAD

**Issue by labixlerOSL** [thelastoutpostworkshop/gpio_viewer#41]
Please add a view for the ESP32-S3 dev module. It is a bit different from the ESP32-S3 WROOM-1 board posted. The best image I have is from the Freenove git-hub (https://github.com/Freenove/Freenove_Basic_Starter_Kit_for_ESP32_S3/blob/main/Datasheet/ESP32-S3%20Pinout.pdf)

**Comment by thelastoutpostworkshop** [comment]
The board is now available
