### ISSUE TITLE
Digital pins not shown

### ISSUE THREAD

**Issue by drewshz** [thelastoutpostworkshop/gpio_viewer#43]
I have tested with different programs, analog pins are displayed, but digital pins are not shown.

Is there additional initialization required?

**Comment by thelastoutpostworkshop** [comment]
I ma working on a fix, currently digital pins are not showing on ESP Board v2.0.14, they work on v2.0.11

**Comment by drewshz** [comment]
Thanks for the update.

I have checked the return values of analogGetChannel(gpioNum).
The results with my board are 15 for an analog pin and 255 for a digital pin.

Will it be possible to check the revision of the board and adjust the check?

**Comment by thelastoutpostworkshop** [comment]
It's now fixed in the latest release.
