### ISSUE TITLE
Please add the Wemos LOLIN D32 board.

### ISSUE THREAD

**Issue by DonWT** [thelastoutpostworkshop/gpio_viewer#44]
See: https://www.wemos.cc/en/latest/d32/d32.html
and
https://mischianti.org/esp32-wemos-lolin-d32-high-resolution-pinout-and-specs/

Note:  you already have the LOLIN32 Lite, this is a later board.

Thank you,

Don.

**Comment by thelastoutpostworkshop** [comment]
The board is now available.

**Comment by DonWT** [comment]
Thank you so much.  I will try this in the next few days and let you know
if I have any questions.

Don.
