### ISSUE TITLE
Requesting for a pinout - Node MCU ESP32S

### ISSUE THREAD

**Issue by pravin-vaz** [thelastoutpostworkshop/gpio_viewer#47]
Thanks for this lovely library. Requesting for a pinout for the Node MCU ESP32S which seems to have its pin outs labelled incorrectly. 
Cheers
[](https://www.ebay.com.au/itm/155592935820?var=455862717104)

**Comment by thelastoutpostworkshop** [comment]
is it this one : https://esphome.io/devices/nodemcu_esp32.html
