### ISSUE TITLE
Please add board Sh-esp32

### ISSUE THREAD

**Issue by lyenlawner** [thelastoutpostworkshop/gpio_viewer#49]
https://docs.hatlabs.fi/sh-esp32/media/sh-esp32_r2.0.0_top_render.jpg

**Comment by thelastoutpostworkshop** [comment]
What board are you selecting in the Arduino IDE for the Sh-esp32 ?

**Comment by lyenlawner** [comment]
Esp32-vroom-32e

Wiki docs
https://docs.hatlabs.fi/sh-esp32/



David Leonardi
Tel 508-801-1540

**Comment by thelastoutpostworkshop** [comment]
The board is now available.
