### ISSUE TITLE
Changing board does not update pin values until value changes

### ISSUE THREAD

**Issue by plrfishing** [thelastoutpostworkshop/gpio_viewer#51]
Issue is the pin values are not updated when the board selected is changed. If I start with the Generic View then change to ESP32-VROOM-32 board with either 30 or 38 pin the status is not updated until a pin status is changed for all the pins. Seems when different board is selected all the pin values need to be updated for the current state. 

Otherwise the code is working great. I can change the sampling interval inside the main LOOP as conditions change. 

Thank you.

**Comment by thelastoutpostworkshop** [comment]
Yes that is the current behavior, I will add the fix in the next release

**Comment by thelastoutpostworkshop** [comment]
I have made the fix in the web application, it's now live.

**Comment by plrfishing** [comment]
Thanks for the fix and it does work properly changing board selection dropdown.
