### ISSUE TITLE
Keywords file update to show all Methods

### ISSUE THREAD

**Issue by toetoast** [thelastoutpostworkshop/gpio_viewer#52]
Hi, can you please update the "keywords.txt" file (with the below entries), so that all the Class Method colours adjust accordingly in the IDE.

Thanks
Tony

#######################################
# Methods and Functions (KEYWORD2)
#######################################
begin	KEYWORD2
setPort	KEYWORD2
setSamplingInterval	KEYWORD2
connectToWifi	KEYWORD2
monitorTaskStatic	KEYWORD2

**Comment by thelastoutpostworkshop** [comment]
Thanks it's now added, will be included in the next release
