### ISSUE TITLE
Feature Request: Adding a Tick Box called "Show Legend" to the webpage

### ISSUE THREAD

**Issue by toetoast** [thelastoutpostworkshop/gpio_viewer#57]
What do you think about adding a new feature to the webpage that is enabled via a tick box called "Show Legend".
Once ticked, this would make the selected ESP32 "Board Legend" visible on the page.

The advantage with this feature is that you can see more details about the function of each GPIO alongside the current status.
I've made a mock-up screen shown here to simulate what this could look like.

For most of the supported boards, the legend is in the Repo anyway, so I thought this would make sense to utilise the asset.

Cheers
Tony

![Show Legend Feature](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/65843197/71ef864b-8235-41e6-8244-2cdbdcb5d1cf)

**Comment by thelastoutpostworkshop** [comment]
Greate Idea!

**Comment by toetoast** [comment]
No worries. Happy to help where I can.

**Comment by thelastoutpostworkshop** [comment]
I can detect touch and ADC pins, but no other pin functions, there is no API in the ESP32 core to get that information.
I have submitted it to Espressif.
As of now you can see in the web application pins that have touch functions or ADC functions.
To see which one, you have to click on a pin for now.
