### ISSUE TITLE
ERROR: Too many messages queued

### ISSUE THREAD

**Issue by Marcelverhoeven** [thelastoutpostworkshop/gpio_viewer#59]
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/47078286/9ce0736b-d419-4d0b-ac16-ce35a94986b2)

I installed the Libraries in PLATFORMIO and yes SUCCESS!
Thanks again for this fantastic solution!
But as you can see in the picture the Library generates an ERROR reported on the serial monitor while in my opinion there is no error: hence my question: can the serial monitoring communication be improved?

**Comment by thelastoutpostworkshop** [comment]
Glad your were able to make it work with PlatformIO.
The messages you see comes from the AsyncTCP library, not from the GPIOViewer library,
There is nothing I can do to improve this.
