### ISSUE TITLE
request PlatformIO.org and MicroBlocks.fun examples

### ISSUE THREAD

**Issue by kgiori** [thelastoutpostworkshop/gpio_viewer#62]
Very cool library. Would be nice if you could build examples for my two favorite programming tools: [PlatformIO](https://pltformio.org) and [MicroBlocks](https://MicroBlocks.fun). We use PIO to build firmware images for MicroBlocks, so ultimately supporting MicroBlocks is my main goal, but PIO is an intermediate step. ;)

**Comment by thelastoutpostworkshop** [comment]
So your were able to make it work with PlatformIO ?
