### ISSUE TITLE
Feature Request: Adding an indicator to show the ESP32 device is sending data to the Webpage

### ISSUE THREAD

**Issue by toetoast** [thelastoutpostworkshop/gpio_viewer#63]
There can be times that the GPIOs are actually static (no change in state) and that can be by design according to the code running on the ESP32. At this point the webpage LEDs are no longer changing. However, there may be fault conditions as shown below.

There could be situations like:
1. The ESP32 has lost connection to WiFi.
2. The ESP32 task for polling the GPIOs has stopped.
3. When the ESP32 has been powered off
etc

During any of the above, the Webpage remains static and we don't think anything is wrong. 

What I feel is a useful feature is to add an indicator on the webpage that shows that the ESP32 device is still sending data to the site.
This indicator can flash on screen and maybe it's frequency derived from the Sampling Interval - flashing state toggles per interval maybe?

Having such a flashing indicator on the page is another tool to help with ESP32 fault diagnosis - if the flashing stops then check the board!

Regards
Tony

**Comment by thelastoutpostworkshop** [comment]
That's a very good idea, I add it for a future release.
Thanks You.
