### ISSUE TITLE
Board layout for Lolin/Wemos "ESP32-C3-Mini", two board revisions

### ISSUE THREAD

**Issue by sfromis** [thelastoutpostworkshop/gpio_viewer#64]
Nice tool :smile: 

I have a couple of observations about the support for this.
https://github.com/thelastoutpostworkshop/microcontroller_devkit/blob/main/gpio_viewer/assets/html/ESP32-C3-Mini.html
https://github.com/thelastoutpostworkshop/microcontroller_devkit/blob/main/gpio_viewer/assets/devboards_images/ESP32-C3-Mini.png

In addition to the broken-out pins for soldering, the bottom right button in the board image is gpio 9, and thus also relevant for showing in a similar way as other pins. Even room for the colored dot.

As the gpio 7 neopixel in that corner is the same pin as gpio 7 to the right, I suppose that this arguably is sufficient representation.

The revision matching the images is the v2.1.0 design, matching the updated version improving on the antenna design, and replacing a plain led with the neopixel. The original v1.0.0 revision has further differences, as the pinout is not the same.
https://www.wemos.cc/en/latest/c3/c3_mini_1_0_0.html
https://www.wemos.cc/en/latest/_static/boards/c3_mini_v1.0.0_1_16x16.jpg
https://www.wemos.cc/en/latest/_static/boards/c3_mini_v1.0.0_4_16x9.jpg
The older variant v1.0.0 has the left column of pins as EN,0,1,2,3,4,5,3V3 instead of EN,3,2,1,0,4,5,3V3. Go figure.

Hopefully the older variant is becoming "less common" as the bad antenna design was not good for Wifi, with the workaround of lower send power sometimes helping. I've not ditched the older boards I bought, but they are not "preferred" to use.

**Comment by thelastoutpostworkshop** [comment]
Thanks for pointing out the missing GPIOs.
I have added GPIO 9, but the current release do not support GPIO that can be at two different places on the board like GPIO 7.
I have added that for a future release.
