### ISSUE TITLE
Wemos/Lolin S3 Mini board

### ISSUE THREAD

**Issue by sfromis** [thelastoutpostworkshop/gpio_viewer#66]
Very similar to the S2 Mini board, there's also a board with ESP32-S3FH4R2.
https://www.wemos.cc/en/latest/s3/s3_mini.html

Nearly all pins are placed differently. And gpio 47 bottom right is a neopixel, near the gpio0 button.

**Comment by thelastoutpostworkshop** [comment]
The board is now available
