### ISSUE TITLE
Add modules or even chips as "boards" in the layouts?

### ISSUE THREAD

**Issue by sfromis** [thelastoutpostworkshop/gpio_viewer#69]
Seeing https://github.com/thelastoutpostworkshop/gpio_viewer/issues/68 "inspired" me to suggest the board layouts to include setups for the "raw" standard modules (and maybe even chips). While this obviously is not as easily accessible for wiring, it would visualize all pins, and can be helpful to people analyzing existing hardware, which is not based on a development board.

**Comment by thelastoutpostworkshop** [comment]
Yes it could be nice to add them.  Do you have image examples ?
