### ISSUE TITLE
ESP32 WROOM-32 board support

### ISSUE THREAD

**Issue by jlit** [thelastoutpostworkshop/gpio_viewer#7]
Love the library.  Would love support for the [ESP32 WROOM-32](https://www.amazon.com/gp/product/B08D5ZD528/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1) boards.  Similar looking to the ESP32-VROOM-32D but with different pinout.   

![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/6777327/2abde49c-35bb-4264-9a69-bc59efa4bb6c)

![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/6777327/861d11be-82b8-447e-96d8-f104b228501d)

Thanks.

**Comment by jlit** [comment]
Here's an image that lines up with the ESP32-VROOM-32D image:
![ESP32-WROOM-32](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/6777327/da66026d-7966-4925-bef7-f121203be345)

**Comment by thelastoutpostworkshop** [comment]
The board is now available.
