### ISSUE TITLE
NodeMCU ESp8266

### ISSUE THREAD

**Issue by paulsjvr** [thelastoutpostworkshop/gpio_viewer#77]
Hi
Please Add NodeMCU ESp8266 to GPIO viewer.

Thanx for the great work.

Paul

**Comment by thelastoutpostworkshop** [comment]
I am not sure if ESP8266 will be compatible, I will do some testing

**Comment by arendst** [comment]
Try Tasmota dev branch. Already fitted with a functional adaptation of gpio_viewer and tested on ESP8266 and all current ESP32 derivatives like ESP32-C3 but also -C2 and -C6 using Arduino Core 3.0

![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/11044339/596090cc-a006-4dff-8724-2a9b3a649e22)

The above picture is from an wemos Di mini (ESP8266) running Tasmota v13.30.2

See here for adaptations (mainly removing some ESP32 specifics) https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota_xdrv_driver/xdrv_121_gpioviewer.ino

**Comment by paulsjvr** [comment]
> Try Tasmota dev branch. Already fitted with a functional adaptation of gpio_viewer and tested on ESP8266 and all current ESP32 derivatives like ESP32-C3 but also -C2 and -C6 using Arduino Core 3.0
> 
> ![image](https://private-user-images.githubusercontent.com/11044339/295037756-596090cc-a006-4dff-8724-2a9b3a649e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODY3NTMsIm5iZiI6MTcwNDc4NjQ1MywicGF0aCI6Ii8xMTA0NDMzOS8yOTUwMzc3NTYtNTk2MDkwY2MtYTAwNi00ZGZmLTg3MjQtMmE5YjNhNjQ5ZTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA3NDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OTE4MmJiZTgyZDkzODA4Mjk3OWU1Nzk2M2VhMjJhNDAwY2ZjOTA1ZGE4ZGFkOTVhNmEzOGY4ZmU1NmQ4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PqHIIqPyYqmW0_tcX2obMv0ZbXsgjQV0fjwUFbkI-5k)
> 
> The above picture is from an wemos Di mini (ESP8266) running Tasmota v13.3.0.2
> 
> See here for adaptations (mainly removing some ESP32 specifics) https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota_xdrv_driver/xdrv_121_gpioviewer.ino

Awesome
Thanx Theo, I will give it a try.
