### ISSUE TITLE
'analogGetChannel' was not declared in this scope

### ISSUE THREAD

**Issue by samarkh** [thelastoutpostworkshop/gpio_viewer#79]
This could be the same as issue #74 
When I try the basic Platformio example I get
 'analogGetChannel' was not declared in this scope
 gpio_viewer.h, line 374
platformio.ini

```
[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit

framework = arduino
monitor_speed = 115200
upload_speed = 1500000
monitor_port = COM11
upload_port = COM11
lib_deps =
            thelastoutpostworkshop/GPIOViewer @ ^1.0.7
            https://github.com/me-no-dev/ESPAsyncWebServer.git
            https://github.com/dvarrel/AsyncTCP.git
            https://github.com/me-no-dev/ESPAsyncWebServer.git
build_flags = 
  -D CORE_DEBUG_LEVEL=5

```
Any sugestions?
Yours Simon M

**Comment by thelastoutpostworkshop** [comment]
You need tp update your platform espressif32 to the latest version (2.0.14)

**Comment by toetoast** [comment]
If for some reason you need the installed Espressif Systems ESP32 Board (accessed via Arduino Boards Manager) to be less then 2.0.14 then the lowest you can go for compatibility is 2.0.5 as shown here.

The documentation within the README file has now been updated to reflect this.

Tony

![Wed 10-01-2024 4-30-28 AM](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/65843197/f71b7595-813b-4d6f-b11f-60717b52f5a6)

**Comment by samarkh** [comment]
Many thanks
`PlatformIO Core CLI → pio pkg update -g -p espressif32 `
worked a charm
