### ISSUE TITLE
ESP32-DevKitC-32D support

### ISSUE THREAD

**Issue by michmela44** [thelastoutpostworkshop/gpio_viewer#8]
Would be nice to have this common module added

[To Buy](https://www.digikey.com/en/products/detail/espressif-systems/ESP32-DEVKITC-32D/9356990?utm_adgroup=&utm_term=&utm_content=&gad_source=1)

[Reference Image](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/_images/esp32-devkitC-v4-pinout.png)
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/417561/029ed24f-0867-4d4d-844a-1ee21ab988fd)

[DataSheet](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf)

**Comment by thelastoutpostworkshop** [comment]
This board is already available.
