### ISSUE TITLE
Add possibility to close window in case another user opens gpioviewer

### ISSUE THREAD

**Issue by arendst** [thelastoutpostworkshop/gpio_viewer#80]
As Tasmota supports only one instance I needed a solution to close the current GPIOViewer window if another GPIOViewer window is openend.

I solved it by adding the below code to webSocket.js function ``initEventSource()``:
```
  source.addEventListener(
    "close",
    function (e) {
      console.log("Closing");
	  self.close();
    },
    false
  );
```

When I open a second instance of GPIOViewer I call ``event close`` first solving concurrency issues.

**Comment by thelastoutpostworkshop** [comment]
now implemented
