### ISSUE TITLE
Support for LilyGo T-CAN485

### ISSUE THREAD

**Issue by Saentist** [thelastoutpostworkshop/gpio_viewer#82]
https://github.com/Xinyuan-LilyGO/T-CAN485
more challenging design

**Comment by thelastoutpostworkshop** [comment]
Can you identify which poles corresponds to which GPIO ?
![image](https://github.com/thelastoutpostworkshop/gpio_viewer/assets/127604345/1f1fbfbc-a83b-49cb-89a5-9233251fa4e0)

**Comment by Saentist** [comment]
https://github.com/Xinyuan-LilyGO/T-CAN485/blob/main/doc/schematic.pdf
This PDF contain them page3

**Comment by Saentist** [comment]
Not implemented yet.
