### ISSUE TITLE
Please Add WT32-ETH01 Ethernet Module

### ISSUE THREAD

**Issue by LGermanoJr** [thelastoutpostworkshop/gpio_viewer#83]
https://files.seeedstudio.com/products/102991455/WT32-ETH01_datasheet_V1.1-%20en.pdf
https://github.com/egnor/wt32-eth01/blob/main/wt32-eth01.png
https://github.com/ldijkman/WT32-ETH01-LAN-8720-RJ45-/blob/main/wt32prog.jpg

**Comment by thelastoutpostworkshop** [comment]
The board is now available.
