### ISSUE TITLE
Addition of DOIT ESP32 DEVKIT V1

### ISSUE THREAD

**Issue by OhReally-sj** [thelastoutpostworkshop/gpio_viewer#85]
Please consider addition of DOIT ESP32 DEVKIT V1

**Comment by thelastoutpostworkshop** [comment]
Provide a link to your specific board

**Comment by thelastoutpostworkshop** [comment]
yes, but it's already there, it's called ESP32-VROOM-32D in the web application

**Comment by OhReally-sj** [comment]
Ok, thanks.
