### ISSUE TITLE
Add board AI Thinker ESP32-CAM

### ISSUE THREAD

**Issue by dgerontopoulos** [thelastoutpostworkshop/gpio_viewer#87]
I would like to add support for I Thinker ESP32-CAM board.

**Comment by thelastoutpostworkshop** [comment]
please provide a URL to your specific board

**Comment by dgerontopoulos** [comment]
http://www.ai-thinker.com/pro_view-24.html

**Comment by thelastoutpostworkshop** [comment]
The board is now available.
