### ISSUE TITLE
Please add AZ Delivery NodeMCU ESP32

### ISSUE THREAD

**Issue by andreasvp** [thelastoutpostworkshop/gpio_viewer#89]
The Link would be https://cdn.shopify.com/s/files/1/1509/1638/files/ESP_-_32_NodeMCU_Developmentboard_Datenblatt_AZ-Delivery_Vertriebs_GmbH_10f68f6c-a9bb-49c6-a825-07979441739f.pdf?v=1598356497
or the doc with pin line out https://cdn.shopify.com/s/files/1/1509/1638/files/ESP-32_NodeMCU_Developmentboard_Pinout.pdf?v=1609851295

Thanks for the great work!

**Comment by thelastoutpostworkshop** [comment]
The board is now available.

**Comment by andreasvp** [comment]
Excellent! Thanks again
