### ISSUE TITLE
The Wifi icon on the Web UI stops flashing when no GPIO state changes are sent

### ISSUE THREAD

**Issue by toetoast** [thelastoutpostworkshop/gpio_viewer#96]
I've noticed for a while now on version 1.5 that the Web UI Wifi icon stops flashing when no GPIO state changes happen.
This could be misleading for the user, since he/she may think the ESP32 has crashed and not sending any GPIO status data.

I'm thinking that the Wifi icon should flash, even if there are no GPIO state changes - what do you think?

Cheers
Tony

**Comment by thelastoutpostworkshop** [comment]
I have fixed it in the new web app release (v2.0.8).

**Comment by thelastoutpostworkshop** [comment]
Thanks for reporting it
