### ISSUE TITLE
Feature Request: The GPIOViewer Web Application "About" menu item to show its version number

### ISSUE THREAD

**Issue by toetoast** [thelastoutpostworkshop/gpio_viewer#97]
Just an idea that the "About" menu on the "GPIOViewer Web Application" could show the Web App's version number - At the time of writing this is V2.0.8 

One downside of doing this maybe that this number could be confused with the actual Arduino Library version?

Tony

**Comment by thelastoutpostworkshop** [comment]
Good idea, I will put both of them to avoid the confusion

**Comment by thelastoutpostworkshop** [comment]
I have added version releases of both GPIOViewer and the Web Application on the About page.
Refresh the browser page to get v2.0.9 of the web application to see the changes.

**Comment by toetoast** [comment]
Looks real nice 👍
